feathure#0001 Добавлено подтверждение регистрации пользователей через…
honeydev/junior pull request #81
Opened 2019-11-21 03:20 UTC by supereko

… email

2019-11-21 04:12 UTC, honeydev requested changes

2019-11-21 04:12 UTC, honeydev commented on src/templates/email_aprove.html
> +<!DOCTYPE html>
У нас есть базовый темплейт base.html, в котором уже есть базовая структура html документа, от него нужно наследоваться

2019-11-21 04:12 UTC, honeydev commented on src/templates/email_aprove.html
> +</html>
github требует пустую строку в конце каждого файла

2019-11-21 04:12 UTC, honeydev commented on src/user/models.py
> +        try:
Глобальный эксепшен это однозначно плохо, либо отлавливай конкретное исключение, либо совсем убирай.

2019-11-21 04:12 UTC, honeydev commented on .env.example
> +SECRET_KEY = "your_super_secret_key"
Пустая строка

2019-11-22 00:49 UTC, supereko commented on .env.example
> +SECRET_KEY = "your_super_secret_key"
эта строка отделяет настройки почтового клиента от настроек безопасности

2019-11-22 00:50 UTC, supereko commented on src/templates/email_aprove.html
> +<!DOCTYPE html>
Это шаблон для отправки по почте, не для отображения на сайте

2019-11-22 00:56 UTC, merged